language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode

bundler_args: --full-index

before_script:
  - git submodule update --init --recursive

script: bundle exec rspec -c spec/

