language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode

before_script:
  - git submodule update --init --recursive
  - bundle install
  - cd vendor/parser && rake compile

script: bundle exec rspec spec/
